### ISSUE TITLE
Add --resume docker argument as an optional input

### ISSUE THREAD

**Issue by NMNS93** [moka-guys/dnanexus_congenica_upload#2]
The sapientia app raises an error if files have not been uploaded successfully. Subsequently, re-running the app causes it to fail because, due to the partial upload, the app believes the samples are already in sapientia.

The current fix is to run the app in debug mode, ssh into it, and run the Sapientia docker application with the --resume argument.

Instead, we want the argument to be an optional flag on the dna nexus app itself and to document the use-case for this in the readme.

**Comment by aledj2** [comment]
not fixed so hopefully won't automatically close!

**Comment by RachelDuffin** [comment]
Not really required as you can manually delete the IR and re-run the app
